# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '\w*\.txt'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-illegal-windows-names
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: fix-byte-order-marker
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      name: interrogate (Python docstring enforcer)
      args: [--verbose]
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.4
  hooks:
    - id: uv-lock
